{
  try {
    join();
    return 0;
  }
 catch (  InterruptedException e) {
    throw Log.errRTExcept(e);
  }
}
